CREATE TABLE ticket
(
    id       varchar(256) NOT NULL,
    event_id integer      NOT NULL,
    user_id  integer      NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE "user"
(
    id          integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    firstName   varchar(40)  NOT NULL,
    lastName    varchar(40)  NOT NULL,
    email       varchar(40)  NOT NULL,
    birth_date  date         NOT NULL,
    location    integer,
    profile_pic varchar(1024),
    about_me    varchar(2048),
    salt        varchar(256) NOT NULL,
    password    varchar(256) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE event
(
    id          integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    name        varchar(80)   NOT NULL,
    location    integer       NOT NULL,
    description varchar(2048) NOT NULL,
    pictures    integer,
    "start"     timestamp     NOT NULL,
    "end"       timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE location
(
    id         integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    name       varchar(40)      NOT NULL,
    latitude   double precision NOT NULL,
    longitude  double precision NOT NULL,
    created_on timestamp        NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE pictures
(
    event_id integer       NOT NULL,
    url      varchar(1024) NOT NULL,
    PRIMARY KEY (event_id, url)
);
CREATE TABLE friends
(
    userA integer NOT NULL,
    userB integer NOT NULL,
    PRIMARY KEY (userA, userB)
);
ALTER TABLE pictures
    ADD CONSTRAINT FKPictures14710 FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE;
ALTER TABLE "user"
    ADD CONSTRAINT FKUser586969 FOREIGN KEY (location) REFERENCES location (id); -- ON DELETE SET NULL??
ALTER TABLE event
    ADD CONSTRAINT FKEvent894025 FOREIGN KEY (location) REFERENCES location (id); -- ON DELETE SET NULL??
ALTER TABLE ticket
    ADD CONSTRAINT FKTicket579021 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE;
ALTER TABLE ticket
    ADD CONSTRAINT FKTicket634115 FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE;
ALTER TABLE friends
    ADD CONSTRAINT FKFriends788075 FOREIGN KEY (userA) REFERENCES "user" (id) ON DELETE CASCADE;
ALTER TABLE friends
    ADD CONSTRAINT FKFriends788076 FOREIGN KEY (userB) REFERENCES "user" (id) ON DELETE CASCADE;


-- Check constraints
ALTER TABLE "user"
    ADD CONSTRAINT Check_age_over_18 CHECK ( date_part('days', (CURRENT_TIMESTAMP - birth_date::timestamp)) >=
                                             18 * 365 );

ALTER TABLE event
    ADD CONSTRAINT event_start_in_future CHECK ( "start" > CURRENT_TIMESTAMP );

